name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort

    - name: Run isort
      run: isort --check --settings-path=setup.cfg ./**/*.py

    - name: Run black
      run: black --check .

    - name: Run flake8
      run: flake8 --config=setup.cfg .
